Repository climbjios-sg/climbjios-app, pull requests merged in 2022-10, with the labels that each got.

#43 fix: padding bottom
  frontend/src/pages/dashboard/jios/list/index.tsx
  frontend/src/pages/dashboard/profile/index.tsx
Labels: bug.Low

#60 Telegram OAuth
  backend/.env.example
  backend/package.json
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/telegramOauth/telegramOauth.guard.ts
  backend/src/auth/telegramOauth/telegramOauth.module.ts
  backend/src/auth/telegramOauth/telegramOauth.strategy.ts
  backend/src/database/migrations/20221013050501_update-users-email-nullable.ts
  backend/src/utils/constants/constants.service.ts
  backend/src/utils/types.ts
  backend/yarn.lock
  frontend/README.md
  frontend/package.json
  frontend/src/sections/auth/login/LoginForm.tsx
  frontend/src/utils/api.ts
  frontend/yarn.lock
Labels: type.Frontend, type.Backend, difficulty.S, urgency.High

#50 fix jio form nits
  frontend/src/components/FloatingBottomCard.tsx
  frontend/src/pages/auth/Login.tsx
  frontend/src/pages/dashboard/MainApp.tsx
  frontend/src/pages/dashboard/jios/create/index.tsx
  frontend/src/pages/dashboard/jios/edit/index.tsx
  frontend/src/pages/dashboard/jios/form/JiosCreateEditForm.tsx
  frontend/src/pages/dashboard/jios/form/JiosSearchForm.tsx
  frontend/src/pages/dashboard/jios/list/allJios/JioCardList.tsx
  frontend/src/pages/dashboard/jios/list/index.tsx
  frontend/src/routes/paths.ts
Labels: bug.Medium, type.Frontend, difficulty.XS

#76 fix: footer github
  landing/src/partials/Footer.jsx
Labels: bug.Medium

#81 fix: mobile nav and mr issue
  landing/README.md
  landing/src/partials/Footer.jsx
  landing/src/partials/Header.jsx
Labels: bug.High

#80 Fix telegram username form
  frontend/src/pages/dashboard/profile/index.tsx
  frontend/src/pages/onboarding/NewUserProfile.tsx
  frontend/src/sections/auth/login/LoginForm.tsx
  frontend/src/sections/onboarding/UsernameForm.tsx
  frontend/src/sections/profile/ProfileEditForm.tsx
Labels: bug.High, type.Frontend

#82 fix: username form
  frontend/src/sections/onboarding/UsernameForm.tsx
Labels: bug.High

#90 fix: add start date time for jio search
  frontend/src/pages/dashboard/jios/list/allJios/JioCardList.tsx
Labels: bug.High

#89 fix: jio support button
  frontend/src/components/SupportButton.tsx
  frontend/src/config.ts
  frontend/src/pages/dashboard/jios/list/ErrorContent.tsx
  frontend/src/pages/dashboard/jios/list/allJios/JioCard.tsx
  frontend/src/pages/dashboard/jios/list/myJios/MyJioCardList.tsx
Labels: bug.High

#88 fix: format time include min
  frontend/src/utils/formatTime.ts
Labels: bug.Medium
